// Embed generator (T9, ISC-8): `scripts/embed.ts` turns the web output into `server/embedded.gen.ts` through
// `embeddedAssetFor()` of the build contract (T6). Each test builds a throwaway repository root that mirrors the
// real layout (`web/dist/browser/…` beside `server/`), so the relative import specifiers of the generated module
// resolve and bun can import it for real.
import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { EMBED_MANIFEST_PATH, WEB_OUTPUT_DIR, type EmbeddedManifest } from "../server/src/assets.contract.ts";

const SCRIPT = join(import.meta.dir, "..", "scripts", "embed.ts");

const FIXTURE: Record<string, string> = {
  "index.html": "<!doctype html><title>fixture</title>",
  "main-ABCDEFGH.js": "console.log('main');",
  "styles-12345678.css": "body{margin:0}",
  "fonts/inter.woff2": "not really a font",
};

const made: string[] = [];
afterEach(() => {
  for (const dir of made.splice(0)) rmSync(dir, { recursive: true, force: true });
});

/** A temp repository root holding the fixture web output, minus the files named in `without`. */
function fixtureRoot(without: string[] = []): string {
  const root = mkdtempSync(join(tmpdir(), "spectant-embed-"));
  made.push(root);
  for (const [rel, body] of Object.entries(FIXTURE)) {
    if (without.includes(rel)) continue;
    const file = join(root, WEB_OUTPUT_DIR, rel);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, body);
  }
  // Angular writes the license file beside `browser/`, not inside it; it must not be embedded.
  writeFileSync(join(root, "web/dist/3rdpartylicenses.txt"), "licenses");
  return root;
}

function embed(args: string[], env: Record<string, string> = {}) {
  const base = { ...process.env };
  delete base.SOURCE_DATE_EPOCH;
  const proc = Bun.spawnSync(["bun", SCRIPT, ...args], { env: { ...base, ...env }, stdout: "pipe", stderr: "pipe" });
  return { exit: proc.exitCode, stdout: proc.stdout.toString(), stderr: proc.stderr.toString() };
}

const manifestOf = (root: string) => readFileSync(join(root, EMBED_MANIFEST_PATH), "utf8");

describe("scripts/embed.ts", () => {
  test("writes file imports with manifest-relative specifiers, sorted by path", () => {
    const root = fixtureRoot();
    const run = embed(["--root", root], { SOURCE_DATE_EPOCH: "1700000000" });
    expect(run.stderr).toBe("");
    expect(run.exit).toBe(0);

    const text = manifestOf(root);
    expect(text.startsWith("// generated by scripts/embed.ts — do not edit\n")).toBe(true);
    // `main.ts` pulls the manifest into `tsc`; Bun's types cannot model `with { type: "file" }` (T11).
    expect(text.split("\n")[1]).toBe("// @ts-nocheck");
    expect(text.endsWith("export default manifest;\n")).toBe(true);
    expect(text).toContain('import type { EmbeddedManifest } from "./src/assets.contract.ts";');
    expect(text).toContain('import a0 from "../web/dist/browser/fonts/inter.woff2" with { type: "file" };');
    expect(text).toContain('import a1 from "../web/dist/browser/index.html" with { type: "file" };');
    expect(text).toContain('import a2 from "../web/dist/browser/main-ABCDEFGH.js" with { type: "file" };');
    expect(text).toContain('import a3 from "../web/dist/browser/styles-12345678.css" with { type: "file" };');
    expect(text).toContain("export const manifest: EmbeddedManifest = {");
    expect(text).toContain("  index: a1,");
    expect(text).toContain('{ path: "/fonts/inter.woff2", file: a0, contentType: "font/woff2", immutable: false },');
    expect(text).toContain('{ path: "/index.html", file: a1, contentType: "text/html; charset=utf-8", immutable: false },');
    expect(text).toContain('{ path: "/main-ABCDEFGH.js", file: a2, contentType: "text/javascript; charset=utf-8", immutable: true },');
    expect(text).toContain('{ path: "/styles-12345678.css", file: a3, contentType: "text/css; charset=utf-8", immutable: true },');

    const order = ["/fonts/inter.woff2", "/index.html", "/main-ABCDEFGH.js", "/styles-12345678.css"].map((p) => text.indexOf(`path: "${p}"`));
    expect(order).toEqual([...order].sort((a, b) => a - b));
    expect(text).not.toContain("3rdpartylicenses");
    expect(text).not.toContain(root); // no absolute path in the generated output
    expect(run.stdout).not.toContain(root);
  });

  test("the generated module imports under bun and exposes the manifest", async () => {
    const root = fixtureRoot();
    expect(embed(["--root", root]).exit).toBe(0);
    const mod = (await import(join(root, EMBED_MANIFEST_PATH))) as { manifest: EmbeddedManifest; default: EmbeddedManifest };
    expect(mod.default).toBe(mod.manifest);
    expect(mod.manifest.assets.length).toBe(4);
    expect(mod.manifest.assets.map((a) => a.path)).toEqual(["/fonts/inter.woff2", "/index.html", "/main-ABCDEFGH.js", "/styles-12345678.css"]);
    expect(await Bun.file(mod.manifest.index).text()).toBe(FIXTURE["index.html"] ?? "");
    for (const asset of mod.manifest.assets) expect(await Bun.file(asset.file).exists()).toBe(true);
  });

  test("SOURCE_DATE_EPOCH fixes generatedAt and makes the output byte-reproducible", () => {
    const root = fixtureRoot();
    expect(embed(["--root", root], { SOURCE_DATE_EPOCH: "1700000000" }).exit).toBe(0);
    const first = manifestOf(root);
    expect(first).toContain('  generatedAt: "2023-11-14T22:13:20.000Z",');
    expect(embed(["--root", root], { SOURCE_DATE_EPOCH: "1700000000" }).exit).toBe(0);
    expect(manifestOf(root)).toBe(first);
  });

  test("an invalid SOURCE_DATE_EPOCH fails the build", () => {
    const root = fixtureRoot();
    const run = embed(["--root", root], { SOURCE_DATE_EPOCH: "yesterday" });
    expect(run.exit).toBe(1);
    expect(run.stderr).toContain("SOURCE_DATE_EPOCH");
  });

  test("exits 1 without index.html and writes nothing", () => {
    const root = fixtureRoot(["index.html"]);
    const run = embed(["--root", root]);
    expect(run.exit).toBe(1);
    expect(run.stderr).toContain("index.html");
    expect(run.stderr).toContain("bun run --cwd web build");
    expect(existsSync(join(root, EMBED_MANIFEST_PATH))).toBe(false);
  });

  test("exits 1 when the web output directory is missing", () => {
    const root = mkdtempSync(join(tmpdir(), "spectant-embed-"));
    made.push(root);
    const run = embed(["--root", root]);
    expect(run.exit).toBe(1);
    expect(run.stderr).toContain(WEB_OUTPUT_DIR);
    expect(run.stderr).toContain("bun run --cwd web build");
  });

  test("--out writes the manifest to the given path", () => {
    const root = fixtureRoot();
    const out = join(root, "elsewhere", "manifest.gen.ts");
    expect(embed(["--root", root, "--out", out]).exit).toBe(0);
    expect(readFileSync(out, "utf8")).toContain('import a1 from "../web/dist/browser/index.html" with { type: "file" };');
    expect(existsSync(join(root, EMBED_MANIFEST_PATH))).toBe(false);
  });

  test("--check passes on a current manifest and fails on a stale or missing one", () => {
    const root = fixtureRoot();
    expect(embed(["--root", root, "--check"]).exit).toBe(1); // nothing generated yet
    expect(embed(["--root", root]).exit).toBe(0);
    const before = manifestOf(root);
    expect(embed(["--root", root, "--check"]).exit).toBe(0); // generatedAt on disk is kept, only assets compare
    expect(manifestOf(root)).toBe(before); // --check never writes

    writeFileSync(join(root, WEB_OUTPUT_DIR, "chunk-ZZZZZZZZ.js"), "export {}");
    const stale = embed(["--root", root, "--check"]);
    expect(stale.exit).toBe(1);
    expect(stale.stderr).toContain("out of date");
  });

  test("rejects an unknown flag", () => {
    const run = embed(["--frobnicate"]);
    expect(run.exit).toBe(1);
    expect(run.stderr).toContain("--frobnicate");
  });
});
