// The one list of icons the app inlines (ISC-18.2). Every name must exist in the pinned `lucide-static` version
// (web/package.json). After changing this list run `bun run --cwd web icons:generate` and commit the regenerated
// `icons.ts`; `web/tests/icons.test.ts` fails while the two disagree.
export const ICON_NAMES = [
  // The old pages' set.
  'activity',
  'arrow-up-down',
  'book-open',
  'check',
  'chevron-down',
  'circle-check',
  'cloud-fog',
  'copy',
  'file-text',
  'filter',
  'gauge',
  'history',
  'layers',
  'layout-dashboard',
  'list-checks',
  'lock',
  'maximize-2',
  'minimize-2',
  'moon',
  'notebook-pen',
  'panel-left-close',
  'panel-left-open',
  'panel-right-close',
  'panel-right-open',
  'rotate-cw',
  'scale',
  'settings',
  'shapes',
  'square-kanban',
  'sun',
  'sun-moon',
  'table',
  'target',
  'timer',
  'triangle-alert',
  'zap',
  // Additions for the new surfaces, from the same pinned version (design.md § Icons).
  'search',
  'x',
  'chevron-right',
  'folder-plus',
  'archive',
  'keyboard',
  'folder-git-2',
  'layout-grid',
] as const;
