/**
 * Build contract between the Angular output and the compiled binary (T6, ISC-8; plan 001 § Approach "Embedding").
 *
 * This file is the seam. Three consumers build against it without talking to each other:
 *
 * 1. `web/` (T7) builds with `baseHref = WEB_BASE_HREF` into `WEB_OUTPUT_DIR`. In `web/angular.json` that means the
 *    application builder's `"outputPath": "dist"` (its `browser` target lands in `dist/browser`) and
 *    `"baseHref": "/"`. Hashed output names stay on (`outputHashing: "all"`, the production default), because
 *    `HASHED_FILENAME` decides which responses may be cached forever.
 *
 * 2. `scripts/embed.ts` (T9) walks `WEB_OUTPUT_DIR` recursively and writes `EMBED_MANIFEST_PATH`. For every file it
 *    calls `embeddedAssetFor(relativePath)` and emits one import with `with { type: "file" }`, so that
 *    `bun build --compile` embeds the file into the binary:
 *
 *    ```ts
 *    // generated by scripts/embed.ts — do not edit
 *    // @ts-nocheck — bun-types cannot type `with { type: "file" }` imports of html/css/ico (T11 finding)
 *    import type { EmbeddedManifest } from "./src/assets.contract.ts";
 *    import a0 from "../web/dist/browser/index.html" with { type: "file" };
 *    import a1 from "../web/dist/browser/main-2GZVUD4R.js" with { type: "file" };
 *    export const manifest: EmbeddedManifest = {
 *      generatedAt: "2026-09-28T10:00:00.000Z",
 *      index: a0,
 *      assets: [
 *        { path: "/index.html", file: a0, contentType: "text/html; charset=utf-8", immutable: false },
 *        { path: "/main-2GZVUD4R.js", file: a1, contentType: "text/javascript; charset=utf-8", immutable: true },
 *      ],
 *    };
 *    export default manifest;
 *    ```
 *
 *    The `file` string that `embeddedAssetFor` returns is the import specifier; the generated source binds `file`
 *    to that import's default export. At runtime the value is whatever Bun resolved (a real path under `bun run`,
 *    a `$bunfs/…` path inside the binary), and in both cases `Bun.file(file)` opens it. `WEB_INDEX` must exist, or
 *    the generator fails the build: a binary without `index.html` would serve nothing.
 *
 * 3. `server/src/http.ts` (T10) serves `manifest.assets` by exact `path` match on `URL.pathname`, with
 *    `Content-Type: contentType` and `Cache-Control: cacheControlFor(immutable)`. Paths under `API_PREFIX` go to the
 *    API. For `isSpaRoute(pathname)` it returns `Bun.file(manifest.index)` as `text/html` with
 *    `CACHE_CONTROL.mutable`. Everything else is 404. The server never lists or reads a directory: the binary has
 *    no web folder beside it, only the manifest (ISC-8.1).
 *
 * `server/embedded.gen.ts` is generated at build time and gitignored, because it changes with every web build
 * (new hashes, new `generatedAt`). T9 adds it to `.gitignore`. Because a fresh checkout does not have it, only the
 * CLI entry imports it; `http.ts` takes the manifest as a parameter, so `bun test tests/` stays green before any
 * build has run.
 *
 * All paths here are POSIX and relative to the repository root, never absolute (ISC-3, repo rule on paths).
 */

/**
 * Angular's application builder output for the `browser` target, relative to the repository root. The builder
 * always writes the client bundle into a `browser` subfolder of `outputPath`; `web/dist` keeps the build inside
 * its lane, and the root `.gitignore` entry `dist/` already covers it.
 */
export const WEB_OUTPUT_DIR = "web/dist/browser";

/**
 * The base href the web app is built with. The server mounts the app at the root of its own origin, so every
 * hashed asset URL is absolute from `/` and a deep link like `/w/x/claims` still loads `/main-….js`, not
 * `/w/x/main-….js`.
 */
export const WEB_BASE_HREF = "/";

/** The entry document inside `WEB_OUTPUT_DIR`; the SPA fallback returns it for every client-side route. */
export const WEB_INDEX = "index.html";

/**
 * The generated import manifest, relative to the repository root. Written by `scripts/embed.ts`, never edited by
 * hand, gitignored. It sits in `server/` beside `src/`, so the compile step picks it up from the CLI entry.
 */
export const EMBED_MANIFEST_PATH = "server/embedded.gen.ts";

/**
 * `WEB_OUTPUT_DIR` as seen from the folder of `EMBED_MANIFEST_PATH`. Import specifiers in the generated manifest
 * are relative to the manifest file, so the generator prefixes every asset with this. A test pins it to
 * `posix.relative(dirname(EMBED_MANIFEST_PATH), WEB_OUTPUT_DIR)`, so moving either path breaks the build loudly.
 */
export const MANIFEST_TO_WEB_OUTPUT = "../web/dist/browser";

/** URL prefix of the JSON API. It is never served from the manifest and never falls back to `index.html`. */
export const API_PREFIX = "/api/";

/**
 * URL prefixes of client-side routes: `/w/<slug>/…` deep links into a workspace. The root `/` is an SPA route
 * too; it is matched exactly in `isSpaRoute`, not as a prefix, because every path starts with `/`.
 */
export const SPA_FALLBACK_PREFIXES: readonly string[] = ["/w/"];

/** One embedded file of the web build. */
export type EmbeddedAsset = {
  /** URL path the server answers on, always starting with `/`, POSIX separators: `/main-2GZVUD4R.js`. */
  path: string;
  /**
   * In the generator: the import specifier relative to the manifest, `../web/dist/browser/main-2GZVUD4R.js`.
   * In the generated manifest: the default export of that `with { type: "file" }` import, a path `Bun.file()`
   * opens both under `bun run` and inside the compiled binary.
   */
  file: string;
  /** The `Content-Type` header value, from `contentTypeFor(path)`. */
  contentType: string;
  /** True for hashed filenames (`HASHED_FILENAME`): served with `CACHE_CONTROL.immutable`. */
  immutable: boolean;
};

/** The shape `server/embedded.gen.ts` exports as `manifest` (named) and as its default export. */
export type EmbeddedManifest = {
  /**
   * ISO 8601 build time. The generator uses `SOURCE_DATE_EPOCH` when it is set, so a pinned release build stays
   * byte-reproducible; otherwise the current time.
   */
  generatedAt: string;
  /** Every file under `WEB_OUTPUT_DIR`, `index.html` included, sorted by `path` so the manifest diffs stably. */
  assets: EmbeddedAsset[];
  /** The `file` of `WEB_INDEX`; the body of every SPA fallback response. */
  index: string;
};

/**
 * Content types by lower-case extension. Explicit, because the binary has no filesystem or MIME database to guess
 * from. Text types carry `charset=utf-8` so the browser never sniffs an encoding; binary types carry none.
 * `.js` and `.mjs` use `text/javascript` (RFC 9239); module scripts are refused under any non-JavaScript type.
 * `.map` is JSON (source maps). `.ico` uses `image/x-icon`, the value every browser accepts for a favicon.
 */
export const CONTENT_TYPES: Readonly<Record<string, string>> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml; charset=utf-8",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
};

/**
 * Fallback for an extension outside `CONTENT_TYPES`. `application/octet-stream` makes the browser download rather
 * than render or execute an unknown file, which is the safe failure; the generator still embeds such files, so a
 * new asset type shows up as a wrong header (visible, fixable here) rather than a missing file.
 */
export const DEFAULT_CONTENT_TYPE = "application/octet-stream";

/** The extension of a path's last segment, lower-cased, with its dot; `""` for none or a dotfile. */
function extensionOf(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1);
  const dot = base.lastIndexOf(".");
  return dot > 0 ? base.slice(dot).toLowerCase() : "";
}

/** The `Content-Type` for a URL or file path, by its extension; `DEFAULT_CONTENT_TYPE` when unknown or absent. */
export function contentTypeFor(path: string): string {
  return CONTENT_TYPES[extensionOf(path)] ?? DEFAULT_CONTENT_TYPE;
}

/**
 * A content-hashed filename, tested against the basename: a `-` or `.` separator, then a hash of 8 or more
 * characters, then the extension, at the end of the name.
 *
 * - `[A-Z0-9]{8,}`: Angular's esbuild builder, which names output `main-2GZVUD4R.js`, `chunk-VLFJUI4J.js`,
 *   `styles-5INURTSO.css` and `media/<name>-<HASH>.<ext>` (8 upper-case base32 characters).
 * - `[a-f0-9]{8,}`: the lower-case hex hashes of the older webpack builder (`main.3f2a1b4c5d6e7f80.js`).
 *
 * Case-sensitive on purpose: a lower-case word in an unhashed public file, `fonts/inter-variable.woff2`, must not
 * pass for a hash, or a font replaced in `web/public/` would stay cached for a year. Known blind spot: an
 * all-digit suffix of 8 or more (`report-20260928.png`) counts as a hash; name public files without one.
 */
export const HASHED_FILENAME = /[-.](?:[A-Z0-9]{8,}|[a-f0-9]{8,})\.[A-Za-z0-9]+$/;

/** Whether a path may be cached forever: its basename carries a content hash, and it is not `WEB_INDEX`. */
export function isImmutable(path: string): boolean {
  const base = path.slice(path.lastIndexOf("/") + 1);
  return base !== WEB_INDEX && HASHED_FILENAME.test(base);
}

/**
 * `Cache-Control` values. Hashed assets never change under their name, so the browser keeps them a year without
 * revalidating. Everything else, `index.html` above all, is `no-cache`: always revalidated, so a new binary's
 * `index.html` points at its new hashes on the next load.
 */
export const CACHE_CONTROL = {
  immutable: "public, max-age=31536000, immutable",
  mutable: "no-cache",
} as const;

/** The `Cache-Control` header for an asset's `immutable` flag. */
export function cacheControlFor(immutable: boolean): string {
  return immutable ? CACHE_CONTROL.immutable : CACHE_CONTROL.mutable;
}

/**
 * Whether a request path is a client-side route that gets `index.html` (the SPA fallback). Takes
 * `URL.pathname`, so no query string or fragment.
 *
 * True for exactly `/` and for paths under `SPA_FALLBACK_PREFIXES` (`/w/…`). Never for `API_PREFIX`: a missing
 * API route must be a JSON 404, not an HTML 200. Never when the last segment ends in an extension from
 * `CONTENT_TYPES`: a missing `main-….js` must 404, because an HTML body under a script URL fails as an opaque
 * MIME error. Only known asset extensions count, because workspace slugs are repository basenames and a repository
 * named `example.com` must still open at `/w/example.com`.
 */
export function isSpaRoute(path: string): boolean {
  if (path === "/") return true;
  if (path.startsWith(API_PREFIX)) return false;
  if (!SPA_FALLBACK_PREFIXES.some((prefix) => path.startsWith(prefix))) return false;
  return !(extensionOf(path) in CONTENT_TYPES);
}

/**
 * The manifest entry for one file, from its path relative to `WEB_OUTPUT_DIR` (`main-2GZVUD4R.js`,
 * `media/inter-ABCDEFGH.woff2`). The single place the generator derives `path`, `file`, `contentType` and
 * `immutable`, so the generator and this contract cannot drift. Windows separators are normalised; an empty,
 * absolute or escaping path throws, because it would embed a file from outside the web build.
 */
export function embeddedAssetFor(relativePath: string): EmbeddedAsset {
  const rel = relativePath.replaceAll("\\", "/");
  if (rel === "" || rel.startsWith("/") || rel.split("/").some((segment) => segment === ".." || segment === "")) {
    throw new Error(`embeddedAssetFor: not a path inside ${WEB_OUTPUT_DIR}: ${JSON.stringify(relativePath)}`);
  }
  const path = `/${rel}`;
  return {
    path,
    file: `${MANIFEST_TO_WEB_OUTPUT}/${rel}`,
    contentType: contentTypeFor(path),
    immutable: isImmutable(path),
  };
}
