#!/usr/bin/env bun
/**
 * embed — writes the import manifest that embeds the web build into the binary (T9, ISC-8).
 *
 * Usage: bun scripts/embed.ts                  (writes server/embedded.gen.ts from web/dist/browser)
 *        bun scripts/embed.ts --check          (exit 1 if the manifest on disk is missing or out of date; writes nothing)
 *        bun scripts/embed.ts --out <path>     (writes the manifest to <path> instead)
 *        bun scripts/embed.ts --root <dir>     (treats <dir> as the repository root; used by tests/embed.test.ts)
 *
 * The shape of the output is fixed by the build contract, `server/src/assets.contract.ts` (T6): one
 * `with { type: "file" }` import per file under `WEB_OUTPUT_DIR`, each entry derived by `embeddedAssetFor()`,
 * sorted by `path`, a named `manifest` export and the same object as the default export. Import specifiers are
 * relative to `EMBED_MANIFEST_PATH` (the contract's `MANIFEST_TO_WEB_OUTPUT`), so `--out` elsewhere yields a file
 * whose imports only resolve if it sits at the same depth; it exists for inspection and tests.
 *
 * Determinism: assets are sorted by code unit, the formatting is fixed and the file ends in a newline.
 * `generatedAt` comes from `SOURCE_DATE_EPOCH` (seconds) when set, so a pinned release build is
 * byte-reproducible; otherwise it is the current time. `--check` without `SOURCE_DATE_EPOCH` keeps the
 * `generatedAt` of the file on disk, so the check compares the asset list, not the clock.
 *
 * Fails with exit 1 when the web output or its `index.html` is missing: a binary without `index.html` would serve
 * nothing. Messages name repository-relative paths only, never an absolute one.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  EMBED_MANIFEST_PATH,
  WEB_INDEX,
  WEB_OUTPUT_DIR,
  embeddedAssetFor,
  type EmbeddedAsset,
} from "../server/src/assets.contract.ts";

const HEADER = "// generated by scripts/embed.ts — do not edit";
// `server/src/main.ts` imports the manifest, so `tsc` checks it, but Bun's types cannot model `with { type: "file" }`
// (they type `.html` as an `HTMLBundle`, and `.ico` or `.css` not at all), although each import is a path string at
// runtime. The explicit `EmbeddedManifest` annotation still types the export for its importer (T11).
const NO_CHECK = "// @ts-nocheck";
const BUILD_HINT = "run `bun run --cwd web build` first";

class EmbedError extends Error {}

/** Every file below `dir`, as POSIX paths relative to it. Symlinks are followed; nothing is skipped. */
function walk(dir: string, prefix = ""): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(join(dir, prefix), { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const isDir = entry.isSymbolicLink() ? statSync(join(dir, rel)).isDirectory() : entry.isDirectory();
    if (isDir) files.push(...walk(dir, rel));
    else files.push(rel);
  }
  return files;
}

/** The manifest entries for the web output under `root`, sorted by `path`. */
export function collectAssets(root: string): EmbeddedAsset[] {
  const outputDir = join(root, WEB_OUTPUT_DIR);
  if (!existsSync(outputDir) || !statSync(outputDir).isDirectory()) {
    throw new EmbedError(`web output not found at ${WEB_OUTPUT_DIR}; ${BUILD_HINT}`);
  }
  const assets = walk(outputDir).map(embeddedAssetFor);
  assets.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  if (!assets.some((asset) => asset.path === `/${WEB_INDEX}`)) {
    throw new EmbedError(`${WEB_OUTPUT_DIR}/${WEB_INDEX} is missing, so the binary would serve nothing; ${BUILD_HINT}`);
  }
  return assets;
}

/** `generatedAt` from `SOURCE_DATE_EPOCH` (whole seconds) when set, else from `now`. */
export function generatedAtFrom(epoch: string | undefined, now = new Date()): string {
  if (epoch === undefined || epoch === "") return now.toISOString();
  if (!/^\d+$/.test(epoch)) throw new EmbedError(`SOURCE_DATE_EPOCH must be whole seconds since 1970, got ${JSON.stringify(epoch)}`);
  return new Date(Number(epoch) * 1000).toISOString();
}

/** The source of `server/embedded.gen.ts` for the given assets, in the exact shape the contract header shows. */
export function renderManifest(assets: EmbeddedAsset[], generatedAt: string): string {
  const name = (i: number) => `a${i}`;
  const indexAt = assets.findIndex((asset) => asset.path === `/${WEB_INDEX}`);
  const lines = [
    HEADER,
    NO_CHECK,
    'import type { EmbeddedManifest } from "./src/assets.contract.ts";',
    ...assets.map((asset, i) => `import ${name(i)} from ${JSON.stringify(asset.file)} with { type: "file" };`),
    "export const manifest: EmbeddedManifest = {",
    `  generatedAt: ${JSON.stringify(generatedAt)},`,
    `  index: ${name(indexAt)},`,
    "  assets: [",
    ...assets.map(
      (asset, i) =>
        `    { path: ${JSON.stringify(asset.path)}, file: ${name(i)}, contentType: ${JSON.stringify(asset.contentType)}, immutable: ${String(asset.immutable)} },`,
    ),
    "  ],",
    "};",
    "export default manifest;",
  ];
  return `${lines.join("\n")}\n`;
}

/** The `generatedAt` value of an existing manifest's source, if it has one. */
function generatedAtOf(source: string): string | undefined {
  const match = /^ {2}generatedAt: "([^"]+)",$/m.exec(source);
  return match?.[1];
}

type Options = { root: string; out?: string; check: boolean };

function parseArgs(argv: string[]): Options {
  const options: Options = { root: resolve(import.meta.dir, ".."), check: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] ?? "";
    if (arg === "--check") options.check = true;
    else if (arg === "--out" || arg === "--root") {
      const value = argv[++i];
      if (!value) throw new EmbedError(`${arg} needs a path`);
      if (arg === "--out") options.out = resolve(value);
      else options.root = resolve(value);
    } else throw new EmbedError(`unknown argument ${arg}; usage: bun scripts/embed.ts [--check] [--out <path>] [--root <dir>]`);
  }
  return options;
}

function main(argv: string[]): number {
  const options = parseArgs(argv);
  const target = options.out ?? join(options.root, EMBED_MANIFEST_PATH);
  const shown = options.out ? "--out path" : EMBED_MANIFEST_PATH;
  const assets = collectAssets(options.root);
  const onDisk = existsSync(target) ? readFileSync(target, "utf8") : undefined;
  const epoch = process.env.SOURCE_DATE_EPOCH;

  if (options.check) {
    if (onDisk === undefined) {
      console.error(`embed: ${shown} does not exist; run \`bun scripts/embed.ts\``);
      return 1;
    }
    const keepClock = epoch === undefined || epoch === "" ? generatedAtOf(onDisk) : undefined;
    const expected = renderManifest(assets, keepClock ?? generatedAtFrom(epoch));
    if (expected !== onDisk) {
      console.error(`embed: ${shown} is out of date with ${WEB_OUTPUT_DIR}; run \`bun scripts/embed.ts\``);
      return 1;
    }
    console.log(`embed: ${shown} is current (${assets.length} assets)`);
    return 0;
  }

  const source = renderManifest(assets, generatedAtFrom(epoch));
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, source);
  console.log(`embed: wrote ${shown} (${assets.length} assets)`);
  return 0;
}

if (import.meta.main) {
  try {
    process.exit(main(process.argv.slice(2)));
  } catch (error) {
    if (!(error instanceof EmbedError)) throw error;
    console.error(`embed: ${error.message}`);
    process.exit(1);
  }
}
